spring:
  application:
    name: technical-test-renderer

server:
  port: 8087

webclient:
  api:
    technical:
      port: 8086
      url: http://localhost:${webclient.api.technical.port}
      base-path: /
      flight-path: /flight

